!include <C4/C4_Container>

!unquoted procedure SatelElementStyle($client)
  !if (%lower($client) == 'satel')
    !$built = "built in this project"
    !$external = "Third party"
  !else
    !$built = " built by Satel"
    !$external = $client + "'s"
  !endif

  UpdateElementStyle("person", $PERSON_BG_COLOR, $ELEMENT_FONT_COLOR, $PERSON_BORDER_COLOR, $legendText="User")

  UpdateElementStyle("system", $SYSTEM_BG_COLOR, $ELEMENT_FONT_COLOR, $SYSTEM_BORDER_COLOR, $legendText=System $built)
  UpdateElementStyle("external_system", $EXTERNAL_SYSTEM_BG_COLOR, $ELEMENT_FONT_COLOR, $EXTERNAL_SYSTEM_BORDER_COLOR, $legendText=$external system)

  UpdateElementStyle("container", $CONTAINER_BG_COLOR, $ELEMENT_FONT_COLOR, $CONTAINER_BORDER_COLOR, $legendText=Container $built)
  UpdateElementStyle("external_container", $EXTERNAL_CONTAINER_BG_COLOR, $ELEMENT_FONT_COLOR, $EXTERNAL_CONTAINER_BORDER_COLOR, $legendText=$external container)
!endprocedure


!unquoted procedure SatelDiagramTitle($client, $project, $diagramType)
  title $client - $project\n$diagramType diagram
!endprocedure


!unquoted procedure SatelDiagramBase($client)
  SatelElementStyle($client)

  right footer %date("yyyy-MM-dd")
!endprocedure


!unquoted procedure SatelContextDiagram($client, $project)
  SatelDiagramBase($client)

  SatelDiagramTitle($client, $project, "Context")
!endprocedure


!unquoted procedure SatelContainerDiagram($client, $project)
  SatelDiagramBase($client)

  SatelDiagramTitle($client, $project, "Container")
!endprocedure


!unquoted procedure SatelDeploymentDiagram($client, $project)
  !include <C4/C4_Deployment>
  SatelDiagramBase($client)

  SatelDiagramTitle($client, $project, "Deployment")
!endprocedure


!unquoted procedure SatelSequenceDiagram($client, $project, $sequence)
  !includeurl https://raw.githubusercontent.com/hillairet/C4Seq-Plantuml/main/c4seq.puml

  ' The legend is problematic to get if we can even get it so don't bother with that
  right footer %date("yyyy-MM-dd")

  SatelDiagramTitle($client, $project, "$sequence\nSequence")

  'Since we typically include all the containers, people and external systems
  'from the other diagrams we need to hide those that are not used/linked
  hide unlinked
!endprocedure
