@startuml
!startsub BASE_INCLUDES
!includeurl https://raw.githubusercontent.com/SatelCreative/satel-c4-plantuml/main/C4Satel.puml
''Include the logos used for the externals in this startsub:
!include <logos/shopify>
!include <logos/aws-ses>


!$CLIENT="Satel"
!$PROJECT="SuperCool app"
!endsub

SatelContextDiagram($CLIENT, $PROJECT)

''Limit the width of the messages on arrows
'skinparam maxMessageSize 100

!startsub BASE_EXTERNALS
Person(customer, "Customer")
Person(manager, "Store manager")
System_Ext(shopify, "Shopify store", "Store equipped with the SuperCool app", $sprite=shopify)
System_Ext(email, "Email service", "AWS SES", $sprite=aws-ses)
!endsub

System(app, "SuperCool app", "A Shopify app that will change the world")

Rel_D(customer, shopify, "Purchases products on")

Rel_R(app, shopify, "Installs as embedded app into")
Rel_L(shopify, app, "Sends new customers to")

Rel_U(app, email, "Triggers email in")

Rel_R(email, customer, "Sends email to")

Rel_U(manager, app, "Manages app and its settings in")

SHOW_LEGEND()

@enduml
